// import {Platform} from 'react-native';

export default {
  DEFAULT_MARGIN: 10,
  DEFAULT_PADDING: 10,

  SMALL_BORDER_RADIUS: 5,
  DEFAULT_BORDER_RADIUS: 10,
  LARGE_BORDER_RADIUS: 20,

  DEFAULT_REGULAR_FONT: 'BalooTammudu2-Regular',
  DEFAULT_BOLD_FONT: 'BalooTammudu2-Bold',

  SMALL_FONT_SIZE: 10,
  NORMAL_FONT_SIZE: 16,
  MEDIUM_FONT_SIZE: 26,
  LARGE_FONT_SIZE: 36,

  TINY_ELEM_DIMS: 20,
  SMALL_ELEM_DIMS: 40,
  MEDIUM_ELEM_DIMS: 80,
  LARGE_ELEM_DIMS: 160,
};
