// import {Platform} from 'react-native';

export default {
  APP_PRIMARY_BG_COLOR: '#4F6367',
  APP_ALTERNATE_BG_COLOR: '#EEF5DB',
  APP_PRIMARY_DARK_BG_COLOR: '#EEF5DB',
  APP_PRIMARY_LIGHT_BG_COLOR: '#4F6367',
  APP_PRIMARY_TEXT_COLOR: '#333333',
  APP_ALTERNATE_TEXT_COLOR: '#FAFAFA',
  APP_TINT_COLOR: '#FFFFFF',
  APP_DARK_TINT_COLOR: '#333333',
  APP_TRANSPARENT_LIGHT_BG_COLOR: 'rgba(255, 255, 255,0.3)',
  APP_TRANSPARENT_DARK_BG_COLOR: 'rgba(79,99,103,0.3)',
};
